spring.application.name=moviewatchlisttracker
spring.datasource.url=jdbc:postgresql://localhost:5432/moviedb
spring.datasource.username=postgres
spring.datasource.password=Gunal@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

tmdb.api.key=e3394071e86204025deecf2c24106ab0
tmdb.base.url=https://api.themoviedb.org/3